name: prism-os
description: Système d'exploitation personnalisé pour la PRISM Steam Machine.

# On se base sur l'image officielle de Bazzite
base-image: ghcr.io/ublue-os/bazzite-deck
image-version: latest # <--- MODIFIÉ ICI (stable -> latest)

modules:
  # 1. On active ton script personnalisé (pour le logo et le fond d'écran)
  - type: script
    scripts:
      - setup-branding.sh
