name: Build ISO
on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Requis pour publier l'ISO dans les Releases
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7

      - name: Generate ISO
        uses: blue-build/github-action@v1
        with:
          recipe: 'recipe.yml'
          build_iso: true
          build_opts: '--no-sign'
          registry_token: '' # <--- IMPORTANT : On vide le jeton pour forcer le téléchargement public anonyme !
