name: Build ISO
on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Generate ISO
        uses: blue-build/github-action@v1
        with:
          recipe: 'recipes/recipe.yml'
          build_iso: true
          no_sign: true # <--- Désactive la vérification des clés
