name: Build ISO
on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Generate ISO
        uses: blue-build/github-action@v1
        with:
          recipe: 'recipe.yml' # <--- On laisse juste 'recipe.yml' !
          build_iso: true
          build_opts: '--no-sign'
